export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const CHANGECOLOR = 'CHANGECOLOR';
export const UPDATEGEOMETRY = 'UPDATEGEOMETRY';
export const UPDATEPATTERN = 'UPDATEPATTERN';