export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const CHANGECOLOR = 'CHANGECOLOR';
export const CHANGEINPUT = 'CHANGEINPUT';
export const UPDATEELLIPSOID = 'UPDATEELLIPSOID';
