export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const CHANGECOLOR = 'CHANGECOLOR';
export const GEOMETRYCHANGED = 'GEOMETRYCHANGED';
export const PROJECTIONCHANGED = 'PROJECTIONCHANGED';
export const UPDATEGEOMETRY = 'UPDATEGEOMETRY';
